from enum import Enum


class SoftCleaningPrices(Enum):
    PRICE_WITHOUT_WINDOWS = 90
    PRICE_WITH_WINDOWS = 170
    PRICE_DAY_VISIT = 0
    PRICE_EVENING_VISIT = 700
    PRICE_NIGHT_VISIT = 1200


class CapitalCleaningPrices(Enum):
    PRICE_WITHOUT_WINDOWS = 150
    PRICE_WITH_WINDOWS = 230
    PRICE_DAY_VISIT = 0
    PRICE_EVENING_VISIT = 700
    PRICE_NIGHT_VISIT = 1200


class ThoroughCleaningPrices(Enum):
    PRICE_WITHOUT_WINDOWS = 120
    PRICE_WITH_WINDOWS = 200
    PRICE_DAY_VISIT = 0
    PRICE_EVENING_VISIT = 700
    PRICE_NIGHT_VISIT = 1200


class AbsolutCleaningPrices(Enum):
    PRICE_WITHOUT_WINDOWS = 150
    PRICE_WITH_WINDOWS = 230
    PRICE_DAY_VISIT = 0
    PRICE_EVENING_VISIT = 700
    PRICE_NIGHT_VISIT = 1200
