from enum import Enum


class Prices(Enum):
    PRICE_WITHOUT_WINDOWS = 90
    PRICE_WITH_WINDOWS = 70
    PRICE_HARD_WORD = 1000
    PRICE_KEYS_DELIVERY = 500
    PRICE_VERY_DIRTY = 1000
    PRICE_DAY_TRIP = 0
    PRICE_EVENING_TRIP = 700
    PRICE_NIGHT_TRIP = 1200
